USE [master]
GO

/****** Object:  Database [SampleBD]    Script Date: 4/13/2020 4:03:23 PM ******/
CREATE DATABASE [SampleBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SampleBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SampleBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SampleBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SampleBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SampleBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SampleBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SampleBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SampleBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SampleBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [SampleBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SampleBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SampleBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SampleBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SampleBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SampleBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SampleBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SampleBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SampleBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SampleBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SampleBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SampleBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SampleBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SampleBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SampleBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SampleBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SampleBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SampleBD] SET RECOVERY FULL 
GO

ALTER DATABASE [SampleBD] SET  MULTI_USER 
GO

ALTER DATABASE [SampleBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SampleBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SampleBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SampleBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SampleBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SampleBD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SampleBD] SET  READ_WRITE 
GO

